### ISSUE TITLE
dateTimePicker 示例出错了

### ISSUE THREAD

**Issue by LeeJim** [TDesignOteam/tdesign-miniprogram#25]
只有月日的示例出错了，如下：

![wecom-temp-06428d2e87101ae05ca8fa7418bc44ea](https://user-images.githubusercontent.com/7017290/145776936-a5a088f1-8d05-45e7-ac04-f666497f4c6a.jpg)

**Comment by wutianSweet** [comment]
示例代码没有出入 year 导致 dayjs 解析日期错误，已修复
